// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCAZ1ffMM9NjFw0Be8GLlYV6QX-JzZoNOs',
    appId: '1:522531221112:web:9ceb1f11bdc2126359078d',
    messagingSenderId: '522531221112',
    projectId: 'task-d63dd',
    authDomain: 'task-d63dd.firebaseapp.com',
    storageBucket: 'task-d63dd.appspot.com',
    measurementId: 'G-BSX1QRS89W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBb_D4wZqsHd7n55wu-VWQdPdbKYykKhrY',
    appId: '1:522531221112:android:cca972bf7b6346c259078d',
    messagingSenderId: '522531221112',
    projectId: 'task-d63dd',
    storageBucket: 'task-d63dd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhzFD85lFIsxYFtJQnOJwMcn5wRA8p-Fk',
    appId: '1:522531221112:ios:49d423698ecacdb059078d',
    messagingSenderId: '522531221112',
    projectId: 'task-d63dd',
    storageBucket: 'task-d63dd.appspot.com',
    iosBundleId: 'com.example.task',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhzFD85lFIsxYFtJQnOJwMcn5wRA8p-Fk',
    appId: '1:522531221112:ios:72dd0547411a090a59078d',
    messagingSenderId: '522531221112',
    projectId: 'task-d63dd',
    storageBucket: 'task-d63dd.appspot.com',
    iosBundleId: 'com.example.task.RunnerTests',
  );
}
